# Exercise

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

- Logistic Regression
- SVM
- Decision Tree
- Random Forest

In [4]:
import numpy as np

from sklearn.datasets import load_iris

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import cross_val_score

In [5]:
iris = load_iris()

In [7]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [6]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

Logistic Regression

In [27]:
lr_score = cross_val_score(LogisticRegression(solver='liblinear'), iris.data, iris.target, cv=3)
print(lr_score)
np.average(lr_score)

[0.96 0.96 0.94]


0.9533333333333333

Support Vector Machine

In [28]:
svm_score = cross_val_score(SVC(), iris.data, iris.target, cv=3)
print(svm_score)
np.average(svm_score)

[0.96 0.98 0.94]


0.96

Decision Tree

In [29]:
dt_score = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
print(dt_score)
np.average(dt_score)

[0.98 0.92 0.96]


0.9533333333333333

Random Forest

In [30]:
rf_score = cross_val_score(RandomForestClassifier(n_estimators=10), iris.data, iris.target, cv=3)
print(rf_score)
np.average(rf_score)

[0.98 0.92 0.92]


0.94

**Best score so far is from SVM: 96%**