# K-Fold Cross Validation

In [29]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [4]:
digits = load_digits()

In [5]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [9]:
lr = LogisticRegression(solver='liblinear', multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9574074074074074

In [10]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.35185185185185186

In [11]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

`K Fold Cross Validation`

- Basic Example

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

Let's try on dummy data

In [13]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [19]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

Use KFold for our digits dataset example

In [14]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [18]:
lr_score = []
svm_score = []
rf_score = []

In [22]:
for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    print(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test))
    print(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    print(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

0.8948247078464107
0.3806343906510851
0.9482470784641068
0.9532554257095158
0.41068447412353926
0.9415692821368948
0.9098497495826378
0.5125208681135225
0.9198664440734557


In [23]:
for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    lr_score.append(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test))
    svm_score.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    rf_score.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [24]:
print(lr_score)
print(svm_score)
print(rf_score)

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]
[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]
[0.9365609348914858, 0.9382303839732888, 0.9382303839732888]


And, at last we will take the average score from each model to know the model's performance.

In [25]:
print(f'LogisticRegression: {sum(lr_score)/len(lr_score)}')
print(f'SVC: {sum(svm_score)/len(svm_score)}')
print(f'RandomForest: {sum(rf_score)/len(rf_score)}')

LogisticRegression: 0.9193099610461881
SVC: 0.4346132442960489
RandomForest: 0.9376739009460211


`Cross Validation Score Function in sklearn`

In [26]:
from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), digits.data, digits.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [27]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3) # CV is 3 by default -> Cross validation or number of splits

array([0.38063439, 0.41068447, 0.51252087])

In [28]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.94323873, 0.94490818, 0.92821369])

cross_val_score uses stratifield kfold by default

`Parameter tunning using K-Fold Cross Validation`

In [31]:
score1 = cross_val_score(RandomForestClassifier(n_estimators=10),  digits.data, digits.target, cv=10)
np.average(score1)

0.9204314090626939

In [32]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=25),  digits.data, digits.target, cv=10)
np.average(score2)

0.9443327126008689

In [33]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=40),  digits.data, digits.target, cv=10)
np.average(score3)

0.9509993792675356